---
provisioner:
  name: chef_zero

suites:
  - name: default
    run_list:
      - recipe[monitoring::default]
  - name: http
    run_list:
      - recipe[monitoring::http]
  - name: mysql
    run_list:
      - recipe[monitoring::mysql]
  - name: smtp
    run_list:
      - recipe[monitoring::smtp]
