---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[monitoring::default]
  - name: apache
    run_list:
      - recipe[monitoring::apache]
  - name: http
    run_list:
      - recipe[monitoring::http]
  - name: mysql
    run_list:
      - recipe[monitoring::mysql]
  - name: nginx
    run_list:
      - recipe[monitoring::nginx]
  - name: rtv
    run_list:
      - recipe[monitoring::rtv]
