---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: centos-7.1
  - name: fedora-20
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[monitoring::default]
  - name: http
    run_list:
      - recipe[monitoring::http]
  - name: mysql
    run_list:
      - recipe[monitoring::mysql]
  - name: smtp
    run_list:
      - recipe[monitoring::smtp]
  - name: raid-aac
    run_list:
      - recipe[monitoring::raid]
    attributes:
      monitoring:
        raid-type: "aac"
  - name: raid-hp
    run_list:
      - recipe[monitoring::raid]
    attributes:
      monitoring:
        raid-type: "hp"
    excludes:
      - fedora-20
  - name: raid-megaraid
    run_list:
      - recipe[monitoring::raid]
    attributes:
      monitoring:
        raid-type: "megaraid"
  - name: raid-mpt
    run_list:
      - recipe[monitoring::raid]
    attributes:
      monitoring:
        raid-type: "mpt"
  - name: raid-md
    run_list:
      - recipe[monitoring::raid]
    attributes:
      monitoring:
        raid-type: "md"
