---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    authorization:
      sudo:
        users:
          - vagrant
          - centos
        passwordless: true

platforms:
- name: centos-6.5
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 6.5"

suites:
  - name: default
    run_list:
      - recipe[monitoring::default]
  - name: apache
    run_list:
      - recipe[monitoring::apache]
  - name: haproxy
    run_list:
      - recipe[monitoring::haproxy]
  - name: http
    run_list:
      - recipe[monitoring::http]
  - name: mysql
    run_list:
      - recipe[monitoring::mysql]
  - name: nginx
    run_list:
      - recipe[monitoring::nginx]
  - name: rtv
    run_list:
      - recipe[monitoring::rtv]
