#!/bin/sh

case $1 in
  config)
    cat <<'EOM'
graph_title PDF Generation Queue
graph_vlabel PDF queue
graph_category RTV
pdf_queue.label PDF queue
EOM
  exit 0;;
esac

printf "pdf_queue.value "
MYSQL_PWD=$password mysql -N -B -h $host -u $user \
    -e 'select count(*) from pdf_generations;' $name
